### ISSUE TITLE
Inability to access location

### ISSUE THREAD

**Issue by rinigus** [flathub/io.github.rinigus.PureMaps#4]
As in https://github.com/flathub/org.gnome.Weather/issues/1, Pure Maps cannot access location. When compiled with KDE 5.12 platform, I get 

```
flatpak run --socket=system-bus --socket=session-bus io.github.rinigus.PureMaps
...
qt.positioning.geoclue2: Already running
qt.positioning.geoclue2: Already running
qt.positioning.geoclue2: Unable to start the client: "org.freedesktop.DBus.Error.AccessDenied" "Agent rejected 'pure-maps' for user '1000'. Please ensure that 'pure-maps' has installed a valid pure-maps.desktop file."
```

There seem to be new geolocation portal (https://github.com/flatpak/xdg-desktop-portal/issues/50 and https://github.com/flatpak/xdg-desktop-portal/pull/242), not sure how to use it though

**Comment by rinigus** [comment]
When using 7514f319a2f3742c9e31a05478e0d485a5de0d11 all worked well. Let's try to reduce to the minimal changes.

**Comment by ntadej** [comment]
Hi @rinigus, sorry to comment on this old ticket, but I wonder how exactly you solved this issue? I have the same issue with a Qt-based app.

**Comment by rinigus** [comment]
Have you tried to add "--system-talk-name=org.freedesktop.GeoClue2"?

**Comment by ntadej** [comment]
It seems to be a weird bug in Ubuntu 20.04. I accidentally rejected when I was asked for permissions and now I can not find the place to reset this. If I change app ID it works. Sorry for the noise!

**Comment by rinigus** [comment]
No problem. Check maybe Privacy/Location?

**Comment by ntadej** [comment]
Nothing is there. I also tried your app and Gnome Weather and neither show up.
